# [Choice] Alpine version: 3.19 3.18, 3.17, 3.16
ARG VARIANT=3.19
FROM alpine:${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
